baseURL = 'https://Monika-shipship.github.io/'
languageCode = 'zh-cn'
title = 'Monika 的学习笔记'
theme = 'book'

# 新增的 Markdown 渲染器配置
[markup]
  [markup.goldmark.renderer]
    unsafe = true

# 开启搜索索引
[outputs]
  home = [ "HTML", "RSS", "JSON" ]

# 顶部导航菜单
[[menu.main]]
  name = '资源分享'
  url = '/resources'
  weight = 10

[[menu.main]]
  name = '关于我'
  url = '/about'
  weight = 20

# 主题相关配置
[params]
  bookRepo = 'https://github.com/Monika-shipship/Monika-shipship.github.io'
  
  # 外观增强
  bookDarkMode = true
  bookLogo = '/logo.png'
  bookCodeCopy = true
  
  # (重要!) 数学公式支持
  [params.math]
    enable = true