# 网站的根 URL。部署后需要修改成您的网址
baseURL = 'https://example.com/'
# 网站语言
languageCode = 'zh-cn'
# 网站标题
title = '我的物理与数学笔记'
# 使用的主题
theme = 'book'

# 是否生成搜索索引，用于网站内搜索
[outputs]
  home = [ "HTML", "RSS", "JSON" ]

# 主题相关配置
[params]
  # Book 主题的 Logo (可选)
  # bookLogo = 'logo.png'
  # 书籍 Repo 的 URL (可选, 会在右上角显示一个 GitHub 链接)
  bookRepo = 'https://github.com/你的用户名/你的仓库名'
  # (重要!) 开启 KaTeX 支持以渲染数学公式
  [params.math]
    # true 表示全局开启，所有页面都支持数学公式
    enable = true